# Generated by Django 5.2 on 2025-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ptr_id', models.IntegerField(null=True)),
                ('qr_code_link', models.URLField(null=True)),
                ('has_entered', models.BooleanField(default=False)),
                ('got_coffee', models.BooleanField(default=False)),
            ],
        ),
    ]
