# Generated by Django 5.2 on 2025-04-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
