# Generated by Django 5.2 on 2025-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_attendee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
