# Generated by Django 5.2 on 2025-04-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0003_attendee_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
